name: auvnet_flutter_assessment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  hive: ^2.2.3
  image_picker: ^1.1.2
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/images/services_section/
    - assets/images/shortcuts_section/
    - assets/images/resturant/
